spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/app/h2/db/dframe
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**,templates/**
    livereload:
      enabled: true